name: guido
channels:
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - biopython=1.74
  - bowtie=1.0.0
  - gffutils=0.9
  - h5py=2.9.0
  - hdf5=1.10.5
  - matplotlib=3.1.1
  - numpy=1.17.1
  - openssl=1.1.1c
  - pandas=0.25.1
  - pyfaidx=0.5.6
  - pyranges=0.0.77
  - python=3.7.3
  - pyvcf=0.6.8
  - scikit-allel=1.2.1
  - scipy=1.3.1
  - seaborn=0.9.0
  - yaml=0.1.7
  - zarr=2.3.2